version: 1
disable_existing_loggers: false

formatters:
  console:
    "()": app.core.logging.CustomFormatter

  file:
    "()": logging.Formatter
    format: "%(asctime)s [%(levelname)s] [%(filename)s:%(lineno)d] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    level: INFO
    class: logging.StreamHandler
    formatter: console
    stream: ext://sys.stdout

  file:
    level: INFO
    class: logging.FileHandler
    formatter: file
    filename: "./AmiconTest.log"

loggers:
  uvicorn.error:
    level: INFO
    handlers: [console, file]
    propagate: false

  uvicorn.access:
    level: INFO
    handlers: [console, file]
    propagate: false

  uvicorn:
    level: INFO
    handlers: [console, file]
    propagate: false
